### ISSUE TITLE
CI und CD einrichten

### ISSUE THREAD

**Issue by benstoffelen** [three-rocketeers/licensorama#5]

**Comment by petermkr** [comment]
- [ ] Automatic Deployments after successful merge to master
- [ ] Automatic Python unit tests for pull requests
- [ ] Automatic Angular unit tests for pull requests
- [ ] Use Sonarcloud
- [ ] Update Readme (installation process, URLs of live site, sonarcloud and builds)

**Comment by petermkr** [comment]
Pull Request #19 resolves this issue.
